name: Check Git Version

on:
  push:
    branches:
      - main

jobs:
  check-git-version:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Display Git Version
        run: git --version
